name: "Docker Build"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  try-to-build:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3

      - name: Create examples environments.
        run: cp report.env.example report.env; mkdir certs

      - name: Try to build
        run: docker build -t project .;
