name: "Code quality"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  check-code-linter:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 19 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the prettier
        run: npm i -g prettier

      - name: Check the linter
        run: yarn run check-linter
