name: "Security"

on:
  pull_request:
    branches: [ master, develop ]
  push:
    branches: [ master ]

jobs:
  snyk-check-packages:
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-22.04 ]
        node-version: [ 19 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the packages.
        run: yarn install

      - name: Check the packages.
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: ./
